### ISSUE TITLE
아이디어 비교 분석 공유

### ISSUE THREAD

**Issue by gmltjd0911** [chatpie/chatbot#2]

**Comment by gmltjd0911** [comment]
2/3일 3시 마감, 5시 회의

**Comment by hia5314** [comment]
현재 관광지를 제공하는 대한민국 구석구석이라는 웹이나 서비스중인 각종 앱들은 앱을 업데이트 또는 지속적인 개발이 필요하나 카카오톡이나 페이스북과 같은 메신저를 통하여 챗봇을 구현할 경우 챗봇을 서비스 제공자가 디바이스에 따른 고려를 할 필요가 없어지며, 내용을 업데이트 및 수정 또한 서버측에서 수정하고 챗 내용만 수정하면, 서비스 유지 및 보수가 훨씬 수월할 것입니다.

또한 현재 위치를 기반으로 가까운 거리의 관광지를 추천해주는 앱은 드물며 만약 외국인의 경우에 언어의 장벽과 함께 지리적 위치를 알지 못하여 관광지를 파악하기 힘들 가능성이 있기 때문에 현재 위치를 이용하여(ex:카카오톡 지도에서 현재위치를 송신) 주변에 있는 관광지를 지도로 혹은 가까운 관광지를 확인할 수 있도록 하면 좋을 것 같습니다.

(현재의 앱들의 경우 현재 위치로부터 1.5km 3km이내의 관광지를 보여주고 그걸 골라서 그 관광지 내에서 위치를 확인하는 방식이나 반대로 위치를 보고 관광지를 고를 수가 없었습니다.) 

혹여 타겟을 외국인으로 하겠다면 카카오톡 api보다는 페이스북이나 다른 메신저를 고려할 필요도 있을 것으로 생각되며, 구축하는 당시에는 한글로 하더라도 영어로도 서비스가 가능하도록 하는 방안 또한 같이 고려해야할 것으로 보입니다.

한줄 - 위치 기반 및 지도를 고려하여 관광지, 유적 등을 고르고 그 이후 챗봇을 통하여 해당 소개를 받는 것이 가능한 서비스를 구축

**Comment by gmltjd0911** [comment]
## 경쟁제품
1. 대한민국 구석구석(어플) - https://play.google.com/store/apps/details?id=com.visitkorea.kr&hl=ko
2. 방방콕콕(어플) - https://itunes.apple.com/kr/app/bangbangkogkog-yeohaengji/id1083296072?mt=8
3. KAYAK bot(챗봇) - https://www.kayak.co.kr/messenger
4. 검색엔진

보통 우리가 어느지역으로 관광을 갈 때 가장 먼저 쓰는 방법은 네이버나 구글에 '어느지역 가볼만한 곳' 같이 검색을 해보는 방법일 것입니다. 만약 앱을 사용한다면 대한민국 구석구석, 방방콕콕과 같은 앱을 사용할 것으로 판단되고,  챗봇의 형태를 띄고있는 서비스는 여행검색엔진인 KAYAK에서 만든 Facebook messenger 기반의 KAYAK bot등 이 있습니다.

## 차별점 
1. 대한민국 구석구석, 방방콕콕과의 가장 큰 차이점이라고 하면 챗봇의 형태를 띄고있다는 것입니다.
2. kAYAK bot은 특정 관광지의 볼거리에 대한 정보는 제공되지 않고 예산에 맞는 여행지를 추천하는 형식, 예를들면 `700000원으로 갈 수 있는 여행지',이기 때문에 우리가 서비스하려는 `어느지역 볼거리`과는 약간 차별점이 있습니다.

**Comment by piligram** [comment]
주제 : 한국의 관광지에 대해 안내해주는 챗봇
대상 : 한국을 찾아온 영어권의 외국인 관광객 or 그냥 한국어권의 관광객
목적 : 관광객들에게 쉽고 빠르게 관광지에 대한 안내를 제공하는 것

비교할 기존의 어플 : visit korea(안드로이드)

visit korea는 한국 관광 공사에서 영어로 된 한국 여행 가이드 앱이다. 앱은 한국의 관광지나 숙박, 쇼핑, 음식에 대한 안내하고, 또 여행 코스를 추천하며 개인별 플래너를 제공한다. 목적지까지의 이동 경로를 안내하는 기능도 있다.

챗봇만의 차별점

1 옵션의 최적화

기존 관광지 안내앱들은 1. 앱을 디자인하고 2. 그 디자인에 많은 정보를 배치하는 것에 앱의 지면을 대부분 활용하게 된다. 그러나 눈길을 끄는 앱 디자인과 앱 자체의 실용성은 반비례하는 경우가 많다는 점, 그리고 관광지가 아무리 많아도 이용자가 갈 수 있는 관광지는 한정되어 있는 점에서 이러한 다양한 정보는 오히려 이용자에게 과다한 옵션으로 자리할 수 있다.
이에 반해 챗봇의 인터페이스는 앱의 인터페이스와 다르게 시각적 이미지를 선택하는 방식과는 차별화되며, 드러나지 않는 인터페이스 속에서 이용자들에게 최적의 옵션을 순차적으로 제공한다. 이러한 순차적인 옵션을 안내받는 과정에서 이용자는 앱 사용에 대한 부담을 최소화할 수 있다.

2 접근성 향상

기존의 관광지 안내앱을 사용하던 이용자는, 자신이 원하는 관광지를 찾기 위하여 앱을 실행한 뒤 그 인터페이스의 많은 옵션 속에서 원하는 관광지를 서치하거나 브라우징 해야 한다. 만약 관광지 안내 챗봇을 쓰게 된다면, 이용자는 자신에게 익숙한 메신저 앱에서 간단한 채팅을 통해 원하는 정보를 얻어낼 수 있을 것이다. 이러한 접근성의 향상은 '원하는 관광지'라는 정보를 찾는 과정의 물리적인 깊이를 줄이는 효과를 가져온다. 또한 채팅이라는 일상적인 행위가 정보를 찾는 과정의 심리적인 깊이를 줄이는 데에도 기여할 수 있다.

3 심화된 개인화

visit korea는 다양한 여행 코스를 제시하고, 그 여행 코스를 플랜화하는 개인화 기능을 제공하고 있다. 하지만 서비스를 이용하기 위해서는 회원가입이 필요하다는 점, 그러한 서비스의 개인화 정도가 미비하다는 단점이 있다.
이에 반해 챗봇은 기존에 사용하던 메신저 기반이기에 회원 가입이 필요 없다는 점, 스마트폰 내의 다른 기능들과의 연동을 통해 좀 더 심도 깊은 개인화된 스케줄을 제공할 수 있다는 장점이 있다.

**Comment by jijiyhan** [comment]
국내 유명 관광지를 추천(안내)해 주는 챗봇

유사 어플: 대한민국 구석구석

어플이 자동으로 gps를 인식하여 현재 위치한 곳의 도시의 여행정보를 한눈에 알 수 있으며 다른 지역의 관광명소, 맛집, 숙박시설 등의 위치, 소개, 평점 등이 나와있다
계절, 테마, 지역별 여행코스 추천 및 인기 여행정보 또한 한눈에 파악할 수 있다

앱의 경우 관광지에 대한 정보 뿐만아니라 맛집, 숙박시설, 교통시설 등의 정보들도 알려주는것에 비해 
챗봇은 한계가 있다.

비교적 간단하고 정형화된 질문에 답해주는 챗봇은 여행지에 관한 단순한 정보들을 줄 수는 있어도 여행지를 비교,판단하여 추천해주는 것은 힘들 것같다.
(예: '여기가 좋아,저기가 좋아?' < 같은 질문들)
여행에 고려해야할만한 다양한 요소들, 누구와 함꼐가는지, 인원이나 여행 시기 등을 고려할 수 있는 필터가 필요할것 같다.
