### ISSUE TITLE
[종성]파이썬에서 챗스크립트와 통신할 수 있는 방법 알아내기

### ISSUE THREAD

**Issue by piligram** [chatpie/chatbot#6]
+ 가능하면 통신까지 성공하기

**Comment by hooon2y** [comment]
챗스크립트 서비스와 장고서버간의 연동을 위해서 하는게 맞나요?

**Comment by JPJSJP** [comment]
답이 늦었습니다

넵, 챗스크립트가 import하는 모듈 형식이 아니라, 그 자체로 프로그램(?)이어서
챗스크립트 서버를 띄운 뒤에, 장고 서버에서 소켓으로 챗스크립트 서버와 통신해서, 그 통신한 결과를 장고에서 다시 카톡으로 쏴줘야하는 형식이어서요

카톡 - 장고 - 챗스크립트
의 형식이라 할 수 있겠고,
말씀하신 것처럼 '장고 - 챗스크립트' 부분의 연동을 위한 작업입니다!

**Comment by JPJSJP** [comment]
앗 이건 제 다른 깃아이디입니다! 로그인을 잘못했네요 ㅜㅠ

**Comment by hooon2y** [comment]
아 네
standalone 서비스라면 어떠한 IPC를 이용해서 연동해야되는지 간략하게 써주면 좋겠내요
 ie. socket, http rest api

**Comment by JPJSJP** [comment]
소켓입니다!
