### ISSUE TITLE
[용훈]기존 챗스크립트에 대본 하나를 작성하여 해당 대본이 동작하도록 해보기

### ISSUE THREAD

**Issue by hia5314** [chatpie/chatbot#7]

**Comment by hooon2y** [comment]
튜토리얼을 변경해서 돌려본다고 이해하면 맞을까요?

**Comment by hia5314** [comment]
네 원래 챗스크립트에 기본으로 제공하는 챗봇이 몇가지 존재하는데 해당 챗봇에 제가 작성한 대본을 추가하여 동작하도록 하는 것이 목표입니다

**Comment by hooon2y** [comment]
네 나중에 챗스크립트 튜토리얼이 끝나면 다른사람들 앞에서 간략하게 돌아가는 모습을 보여주는 것도 좋겠네요

**Comment by hia5314** [comment]
넵
