### ISSUE TITLE
[희성] Yellow ID 생성 & Django와 연동

### ISSUE THREAD

**Issue by gmltjd0911** [chatpie/chatbot#8]
에코서버로 구현

**Comment by hooon2y** [comment]
연동하려고하는 특정 api 명을 적어주면 더 좋습니다.

**Comment by gmltjd0911** [comment]
지금은 관광지 정보 api와 연동하는게 아니라 yellow id와 연동하는 단계입니다. 이용자가 yellow id를 통해 메세지를 날리면 똑같은 내용으로 되돌려주는 것까지 구현할 예정입니다.

**Comment by hooon2y** [comment]
네 그래서 그  yellow id 에서 연동하는 api 명을 말한거에요

**Comment by gmltjd0911** [comment]
1) 키보드
GET /keyboard
- 처음에 사용자가 채팅방에 들어왔을때 사용자에게 아래 키보드에 보여질 내용을 리턴해주어야 합니다.

2) 메세지
POST /message
- 자동응답 API에서 제일 핵심인 내용입니다. 사용자가 보내는 메세지/사진/동영상 을 이 API를 통해서 보내고 서버가 처리해서 그에맞는 응답을 해주면 됩니다.

3) 친구추가
POST /friend
- 사용자가 옐로아이디를 친구추가했을때 호출되는 API입니다.

4) 친구차단
DELETE /friend
- 사용자가 옐로아이디를 친구차단했을때 호출되는 API입니다.

5) 채팅방 나가기
DELETE /chat_room
- 사용자가 채팅내용을 삭제했을때 호출되는 API입니다.

이렇게 5개 api를 구현해야하는 것으로 알고잇어요

**Comment by hooon2y** [comment]
굳!
